import type { Metadata } from 'next'
import { Plus_Jakarta_Sans, Geist_Mono, Noto_Serif } from 'next/font/google'
import './globals.css'
import { SidebarProviderWrapper } from './sidebar-provider-wrapper'

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
  fallback: [
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    'Segoe UI',
    'Roboto',
    'Noto Sans',
    'Ubuntu',
    'Cantarell',
    'Helvetica Neue',
    'Arial',
    'Apple Color Emoji',
    'Segoe UI Emoji',
    'Segoe UI Symbol',
    'Noto Color Emoji'
  ]
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const notoSerif = Noto_Serif({
  variable: '--font-noto-serif',
  style: 'italic',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'CodaPet Design System App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${geistMono.variable} ${notoSerif.variable} antialiased`}
      >
        <SidebarProviderWrapper>
          {children}
        </SidebarProviderWrapper>
      </body>
    </html>
  )
}
